name: Main

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.13
          cache: "pip"
      - name: "installation"
        run: |
          pip install -r requirements.txt -r requirements.dev.txt
      - name: "black"
        run: black . --check --diff --color
      - name: "isort"
        run: isort . --check --diff
      - name: "mypy"
        run: mypy
      - name: "pytests"
        run: python -m pytest
